# Generated by Django 3.2.6 on 2021-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_deleted',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
